export const skills = [
  "Semantic & accessible HTML",
  "Error handling",
  "Git",
  "Responsive Web Desigm",
  "React",
  "GitHub Pull Request & Review",
  "JavaScript: ES6+",
  "React Hooks",
  "NPM",
  "Working with API (fetch, axios)",
  "Redux(Toolkit)",
  "Immutability",
  "Promises, Async/Await",
  "Redux-Saga",
  "Markdown",
  "Debugging",
  "React Router",
  "Scrum",
  "Css Flexbox",
  "Css Grid",
  "Trello",
  "Teamwork",
  "CSS BEM convention",
];

export const nextSkills = [
    "JS classes",
    "Unit testing",
    "TypeScript",
    "Cypress",
    "React Context",
    "WebStorm",
    "AI",
]
